// @flow
export const GET_LIST_BILLS = 'GET_LIST_BILLS';
export const GET_LIST_BILLS_SUCCESS = 'GET_LIST_BILLS_SUCCESS';
export const GET_STORE_INFO = 'GET_STORE_INFO';
export const GET_STORE_INFO_SUCCESS = 'GET_STORE_INFO_SUCCESS';
export const GET_TOTAL_BILLS_COUNT = 'GET_TOTAL_BILLs_COUNT';
export const GET_TOTAL_BILLS_COUNT_SUCCESS = 'GET_TOTAL_BILLS_COUNT_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
