// @flow
export default {
  LOADING: 'LOADING',
  INTRO: 'INTRO',
  LOG_IN: 'LOG_IN',
  LOG_IN_BY_STOREID: 'LOG_IN_BY_STOREID',
  TRANSPORT_BILL: 'TRANSPORT_BILL',
  COMFIRM_STORE_STATE: 'COMFIRM_STORE_STATE',
  REPORT_STORE: 'REPORT_STORE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
};
